name: Trigger Netlify Deployment

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy to Netlify
    steps:
      - name: Curl request
        run: curl -X POST -d {} $DEPLOY_HOOK
        env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
